# Generated by Django 2.1.7 on 2019-05-27 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_info', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('club_name', models.CharField(max_length=50)),
                ('event_date', models.DateField(default=datetime.date)),
                ('registrant_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='event_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_attendance.Event'),
        ),
    ]
