# Generated by Django 2.1.7 on 2019-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0002_auto_20190530_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendee_info',
            new_name='attended',
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(default='event name', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='about_event',
            field=models.TextField(default='about event'),
        ),
    ]
