# Generated by Django 2.2.2 on 2019-06-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0004_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attended',
            new_name='attendee',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='registrant_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='id_number',
            new_name='registrant_number',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
    ]
