# Generated by Django 2.2.2 on 2019-06-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_attendance', '0005_auto_20190623_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='event_attendance',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
