# Generated by Django 2.2.2 on 2019-06-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0007_auto_20190625_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='club_name',
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('leader', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_attendance.Event')),
            ],
        ),
    ]
