# Generated by Django 2.2.2 on 2019-06-30 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0009_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='about_event',
            new_name='content',
        ),
        migrations.AddField(
            model_name='event',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
