# Generated by Django 2.2.2 on 2019-07-01 01:06
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0011_auto_20190701_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
