# Generated by Django 2.2.2 on 2019-07-01 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0012_auto_20190701_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
