# Generated by Django 2.2.2 on 2019-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0013_auto_20190701_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
