# Generated by Django 2.2.2 on 2019-07-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0014_auto_20190701_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
