# Generated by Django 2.2.2 on 2019-07-07 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0017_auto_20190707_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
