# Generated by Django 2.2.2 on 2019-07-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0019_auto_20190708_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendee_limits',
            new_name='attendees_limits',
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='club',
            name='events',
        ),
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(to='events_attendance.Event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events_attendance.Attendance', verbose_name='attendee'),
        ),
    ]
