# Generated by Django 2.2.2 on 2019-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0022_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='events_attendance.Event'),
        ),
    ]
