# Generated by Django 2.2.2 on 2019-07-12 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_attendance', '0023_eventregistration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='confirmed',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='time_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events_attendance.Event'),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=None)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_attendance.EventRegistration')),
            ],
        ),
    ]
