# Generated by Django 2.2.2 on 2019-07-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_attendance', '0024_auto_20190712_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='event pictures'),
        ),
    ]
